encoder_driver:
  ros__parameters:
    wheel_radius: 0.05 # meters
    encoder_cpr: 700
    encoder_multiplier: 4 # gearbox shaft resolution in X4 mode
    encoder_odometry_topic: "/odom"

    # pin assignments
    chip: 4
    right_front_a: 24
    right_front_b: 25
    right_rear_a: 8
    right_rear_b: 7
    left_front_a: 1
    left_front_b: 16
    left_rear_a: 20
    left_rear_b: 21
